version: '3'
services:
  postgres:
    image: "postgres:13"
    container_name: "saga-local"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'saga'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'local'
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
volumes:
  my_dbdata:
